include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = ScreenLock
APP_NAME = ScreenLock
ScreenLock_APPLICATION_ICON = ScreenLock.tiff


#
# Resource files
#
ScreenLock_RESOURCE_FILES = \
Resources/ScreenLock.tiff

#
# Header files
#
ScreenLock_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
ScreenLock_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
ScreenLock_OBJC_FILES += \
Main.m

#
# Localization
#
ScreenLock_LANGUAGES = English French
ScreenLock_LOCALIZED_RESOURCE_FILES = \
ScreenLock.help \
Localizable.strings \
ScreenLockInfo.plist

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
