include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = Pass
APP_NAME = Pass
Pass_APPLICATION_ICON = pass.tiff

#
# Resource files
#
Pass_RESOURCE_FILES = \
Resources/pass.tiff

#
# Header files
#
Pass_HEADER_FILES = \
MyDelegate.h \
Search.h \
ListController.h \
New.h

#
# Objective-C Class files
#
Pass_OBJC_FILES = \
MyDelegate.m \
Search.m \
ListController.m \
New.m

#
# Other sources
#
Pass_OBJC_FILES += \
Main.m

#
# Localization
#
Pass_LANGUAGES = English French
Pass_LOCALIZED_RESOURCE_FILES = \
Pass.help \
Localizable.strings \
PassInfo.plist

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
