include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = Launcher
APP_NAME = Launcher
Launcher_APPLICATION_ICON = Launcher.tiff


#
# Resource files
#
Launcher_RESOURCE_FILES = \
Resources/Launcher.tiff

#
# Localization
#
Launcher_LANGUAGES = English French
Launcher_LOCALIZED_RESOURCE_FILES = \
Localizable.strings \
LauncherInfo.plist \
Launcher.help

#
# Header files
#
Launcher_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
Launcher_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
Launcher_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
