include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.3
PACKAGE_NAME = OpenDisk
APP_NAME = OpenDisk
OpenDisk_APPLICATION_ICON = OpenDisk.tiff


#
# Resource files
#
OpenDisk_RESOURCE_FILES = \
Resources/OpenDisk.tiff

#
# Header files
#
OpenDisk_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
OpenDisk_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
OpenDisk_OBJC_FILES += \
Main.m

# Localization
OpenDisk_LANGUAGES = English French
OpenDisk_LOCALIZED_RESOURCE_FILES = \
Localizable.strings \
OpenDisk.help \
OpenDiskInfo.plist

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
