include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = Birthday
APP_NAME = Birthday
Birthday_APPLICATION_ICON = Birthday.tiff


#
# Resource files
#
Birthday_RESOURCE_FILES = \
Resources/Birthday.tiff

#
# Localization
#
Birthday_LANGUAGES = English French
Birthday_LOCALIZED_RESOURCE_FILES = \
Localizable.strings \
BirthdayInfo.plist \
Birthday.help

#
# Header files
#
Birthday_HEADER_FILES = \
MyDelegate.h

#
# Objective-C Class files
#
Birthday_OBJC_FILES = \
MyDelegate.m

#
# Other sources
#
Birthday_OBJC_FILES += \
Main.m

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/application.make
